[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061

cert_file=/app/letsencrypt/live/$BASE_URL/fullchain.pem
priv_key_file=/app/letsencrypt/live/$BASE_URL/privkey.pem

method=tlsv1_2
verify_client=no
verify_server=no
allow_reload=yes