[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
external_media_address=$BASE_URL
external_signaling_address=$BASE_URL
external_signaling_port=$SIP_PORT

cert_file=/app/certs/fullchain.pem
priv_key_file=/app/certs/privkey.pem
ca_list_file=/app/certs/chain.pem

method=tlsv1_
verify_client=no
verify_server=no
allow_reload=yes