# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: ${SYNAPSE_SERVER_NAME}
pid_file: /data/homeserver.pid
web_client_location: ${SYNAPSE_WEB_CLIENT_LOCATION}
public_baseurl: ${SYNAPSE_PUBLIC_BASE_URL}
allow_public_rooms_over_federation: false
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
delete_stale_devices_after: 30d
email:
  smtp_host: ${SMTP_HOST}
  smtp_port: ${SMTP_PORT}
  smtp_user: ${SMTP_USERNAME}
  smtp_pass: ${SMTP_PASSWORD}
  force_tls: true
  require_transport_security: true
  enable_tls: true
  tlsname: ${SMTP_HOST}
  notif_from: Your Friendly %(app)s homeserver <noreply@${SYNAPSE_SERVER_NAME}>
  app_name: ${SYNAPSE_APP_NAME}
  enable_notifs: true
  notif_for_new_users: true
  notif_delay_before_mail: 10m
  client_base_url: ${SYNAPSE_CLIENT_BASE_URL}
  validation_token_lifetime: 15m
  subjects:
    message_from_person_in_room: '[%(app)s] You have a message on %(app)s from %(person)s
      in the %(room)s room...'
    message_from_person: '[%(app)s] You have a message on %(app)s from %(person)s...'
    messages_from_person: '[%(app)s] You have messages on %(app)s from %(person)s...'
    messages_in_room: '[%(app)s] You have messages on %(app)s in the %(room)s room...'
    messages_in_room_and_others: '[%(app)s] You have messages on %(app)s in the %(room)s
      room and others...'
    messages_from_person_and_others: '[%(app)s] You have messages on %(app)s from
      %(person)s and others...'
    invite_from_person_to_room: '[%(app)s] %(person)s has invited you to join the
      %(room)s room on %(app)s...'
    invite_from_person: '[%(app)s] %(person)s has invited you to chat on %(app)s...'
    password_reset: '[%(server_name)s] Password reset'
    email_validation: '[%(server_name)s] Validate your email'
admin_contact: ${SYNAPSE_ADMIN_CONTACT}
retention:
  enabled: true
  default_policy:
    min_lifetime: 1d
    max_lifetime: 30d
  allowed_lifetime_min: 1d
  allowed_lifetime_max: 30d
allow_profile_lookup_over_federation: false
allow_device_name_lookup_over_federation: false
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: ${SYNAPSE_DB_USERNAME}
    password: ${SYNAPSE_DB_PASSWORD}
    dbname: ${SYNAPSE_DB_NAME}
    host: ${SYNAPSE_DB_HOST}
    port: ${SYNAPSE_DB_PORT}
    cp_min: 5
    cp_max: 10
log_config: /config/log.config
enable_media_repo: true
media_store_path: /data/media_store
max_upload_size: 100M
media_retention:
  local_media_lifetime: 45d
  remote_media_lifetime: 45d
url_preview_enabled: false
turn_uris: [ "turn:${COTURN_HOST}:${COTURN_UDP_PORT}?transport=udp", "turn:${COTURN_HOST}:${COTURN_TCP_PORT}?transport=tcp" ]
turn_shared_secret: ${COTURN_SECRET}
turn_user_lifetime: 1h
turn_allow_guests: false
enable_registration: false
registration_shared_secret: ${SYNAPSE_REGISTRATION_SHARED_SECRET}
allow_guest_access: false
#session_lifetime: infinite
refreshable_access_token_lifetime: 1h
refresh_token_lifetime: 5w
#nonrefreshable_access_token_lifetime: infinite
enable_metrics: false
report_stats: false
macaroon_secret_key: ${SYNAPSE_MACAROON_SHARED_SECRET}
form_secret: ${SYNAPSE_FORM_SECRET}
signing_key_path: "/config/signing.key"
trusted_key_servers: []
push:
  enabled: true
  include_content: true
  group_unread_count_by_room: true
  jitter_delay: 0s
encryption_enabled_by_default_for_room_type: all
stats:
  enabled: true
forget_rooms_on_leave: false