port: 7880
log_level: info
rtc:
  tcp_port: 7881
  port_range_start: 50500
  port_range_end: 50600
  use_external_ip: false
  node_ip: $PUBLIC_IP
redis:
  address: livekit-redis:6379
keys:
  $LIVEKIT_API_KEY: $LIVEKIT_API_SECRET
turn:
  enabled: true
  domain: $BASE_URL
  udp_port: 3478
  tls_port: 5349
  relay_range_start: $LIVEKIT_TURN_MIN_PORT
  relay_range_end: $LIVEKIT_TURN_MAX_PORT
  cert_file: /app/letsencrypt/live/$BASE_URL/fullchain.pem
  key_file: /app/letsencrypt/live/$BASE_URL/privkey.pem