[internal]

; Internal numbers
exten => _1XX,1,Dial(PJSIP/${EXTEN},30)
same => n,GotoIf($["${DIALSTATUS}"="BUSY"]?busy)
same => n,GotoIf($["${DIALSTATUS}"="NOANSWER"]?noanswer)
same => n,Goto(unavailable)

same => n(busy),Playback(line-busy)
same => n,Hangup()

same => n(noanswer),Playback(vm-nobodyavail)
same => n,Hangup()

same => n(unavailable),Playback(vm-nobodyavail)
same => n,Hangup()

; Incorrect numbers
exten => _X!,1,Answer()
same => n,Playback(invalid)
same => n,Hangup()