[internal]

; Internal numbers
exten => _1XX,1,Dial(${PJSIP_DIAL_CONTACTS(${EXTEN})},30)
same => n,GotoIf($["${DIALSTATUS}"="BUSY"]?busy)
same => n,GotoIf($["${DIALSTATUS}"="NOANSWER"]?noanswer)
same => n,Goto(unavailable)

same => n(busy),Busy(10)
same => n,Hangup(17)

same => n(noanswer),Hangup(19)

same => n(unavailable),Hangup(20)

; Incorrect numbers
exten => _X!,1,Answer()
same => n,Playback(invalid)
same => n,Hangup()

[messages]

; SIP MESSAGE routing
exten => _1XX,1,NoOp(Send SIP MESSAGE to ${EXTEN})
same => n,MessageSend(pjsip:${EXTEN},${MESSAGE(from)})
same => n,Hangup()