help:
	@echo "start-containers             — start all containers"
	@echo "start-socks4                 — start socks4 server"
	@echo "start-socks5                 — start socks5 server"
	@echo "start-nginx                  — start nginx server"
	@echo "start-db                     — start databases"
	@echo "start-mongo                  — start mongo"
	@echo "start-demo                   — start all demo projects"
	@echo "start-timers                 — start timers demo project"
	@echo "stop-containers              — stop all containers"
	@echo "stop-socks4                  — stop socks4 server"
	@echo "stop-socks5                  — stop socks5 server"
	@echo "stop-nginx                   — stop nginx server"
	@echo "stop-db                      — stop databases"
	@echo "stop-mongo                   — stop mongo"
	@echo "stop-demo                    — stop all demo projects"
	@echo "stop-timers                  — stop timers demo project"
	@echo "restart-containers           — restart all containers"
	@echo "restart-socks4               — restart socks4 server"
	@echo "restart-socks5               — restart socks5 server"
	@echo "restart-nginx                — restart nginx server"
	@echo "restart-db                   — restart databases"
	@echo "restart-mongo                — restart mongo"
	@echo "restart-demo                 — restart all demo projects"
	@echo "restart-timers               — restart timers demo project"
	@echo "logs-socks4                  — get socks4 server logs"
	@echo "logs-socks5                  — get socks5 server logs"
	@echo "logs-nginx                   — get nginx logs"
	@echo "logs-mongo                   — get mongo logs"
	@echo "logs-timers                  — get timers demo project logs"
	@echo "status-containers            — get containers stats"
	@echo "podman-load-images           — load images from local copy"
	@echo "podman-cleanup               — clean all podman resources"
	@echo "podman-create-network        — create custom podman network with ipv6 support"
	@echo "schedule-midnight-reboot     — reboot server at midnight"
	@echo "init-demo                    — clone demo projects and install dependencies"
	@echo "refresh-demo                 — completely remove demo projects and reinit them"
	@echo "init-demo                    — clone timers demo project and install dependencies"

# @echo " fail2ban-ssh                            — ssh blocked ips
# @echo " podman-cleanup                            — podman cleaning